### ISSUE TITLE
CoherenceNPMI class of contextualized Topic Model to evaluate a Bertopic model for Portuguese Language.

### ISSUE THREAD

**Issue by nadiafelix** [MilaNLProc/contextualized-topic-models#58] opened 2021-04-07 20:09 UTC
* Contextualized Topic Models version: 1.8.2
* Python version:
* Operating System: IOS

I am trying to use the CoherenceNPMI class of contextualized Topic Model to evaluate a Bertopic model for Portuguese Language.

from contextualized_topic_models.evaluation.measures import CoherenceNPMI
import re
delimiters = '*****', ' '

texts = [doc.split() for doc in comentariosList] # load text for NPMI

regexPattern = '|'.join('(?<={})'.format(re.escape(delim)) for delim in delimiters)
topics_ = [re.split(regexPattern, text.strip()) for text in topics_df['Keywords'].values.tolist()]

npmi = CoherenceNPMI(texts=texts, topics=topics_)
npmi.score(topk=3)

 I had this error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/gensim/models/coherencemodel.py in _ensure_elements_are_ids(self, topic)
    444         try:
--> 445             return np.array([self.dictionary.token2id[token] for token in topic])
    446         except KeyError:  # might be a list of token ids already, but let's verify all in dict

7 frames
KeyError: 'de '

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/gensim/models/coherencemodel.py in <genexpr>(.0)
    445             return np.array([self.dictionary.token2id[token] for token in topic])
    446         except KeyError:  # might be a list of token ids already, but let's verify all in dict
--> 447             topic = (self.dictionary.id2token[_id] for _id in topic)
    448             return np.array([self.dictionary.token2id[token] for token in topic])
    449 

KeyError: 'de '

Can you help me?

**Comment by vinid** [comment] 2021-04-08 07:16
Hi @nadiafelix 

I believe that the problem is in how you get the topic words and the words of your documents. Essentially, all the words in `topics_` should appear in `texts`. The error you get means that there are some words in the topic lists that are not in the text.

I am not sure why you use the regex pattern to get the topics, however, if you look at the error, you can see that it says:

` KeyError: 'de '`

This is probably a word in a topic and should be present in the `texts` list. However, note the space char after the "e". This means that the token is `'de '` and not `'de'`. This can cause a key error since the document is Whitespace separated.

You could remove trailing spaces from all the topic words and see if this solves the error.

**Comment by vinid** [comment] 2021-04-10 18:30
Closing this for now, but ping me again if you need help :)

**Closed by vinid** 2021-04-10 18:30 UTC
