### ISSUE TITLE
The Kitty: Human-in-the-loop Classifier example gives errors and warnings

### ISSUE THREAD

**Issue by marcmaxson** [MilaNLProc/contextualized-topic-models#115] opened 2022-09-23 17:16 UTC
* Contextualized Topic Models version: 2.3.0
* Python version: 3.9
* Operating System: MacOS

### Description

I just ran this example:
https://colab.research.google.com/drive/1ZO6y-laPMnIT6boMwNXK4WNiyAUWUK4L?usp=sharing#scrollTo=4bb8v2YCL904

And there were several errors or warnings. Specifically, it did not recognize the `language` param in  `kt.train(training, topics=5, embedding_model="paraphrase-distilroberta-base-v2", language="english")`  and I get hundreds of these warnings during training:

```
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

Presumably, the internal train step is making huggingface angry (hard to believe, I know).

It would be nice if your examples gave no warning when tested verbatim. The only change I made was to use the latest version instead of the one specified in the example.

**Comment by vinid** [comment] 2022-09-23 20:27
Hello @marcmaxson!

thanks for this! 

For the error: we forgot to update the notebook after the release of the new version. `language` was replaced by `stopwords_list` in the latest version. Sorry about that, I have now fixed the notebook.

For the warnings: Yes I think the problem is indeed in the data loader. You might have already found this, but to remove the warning you can do:

```import os
os.environ["TOKENIZERS_PARALLELISM"] = "false
```

code comes from [here](https://stackoverflow.com/questions/62691279/how-to-disable-tokenizers-parallelism-true-false-warning), more details about the issue [here](https://github.com/huggingface/transformers/issues/5486)

**Closed** 2022-09-29 21:08 UTC
